version: 1.2.0.{build}

image: Visual Studio 2019

branches:
  only:
    - master

environment:
  github_access_token:
    secure: 4G1mCBwre8aBHHvMqQA5p7B3gs2Nzr6NtrYbYMzQfjhsXMredvjfjHDpA7ccZ/+G
  github_email:
    secure: 6cDUHrE1dLlH77vY5fZjHXJ4+b7/pHYSFp9ELxBCOyU=

install:
  - cinst docfx

build_script:
- pwsh: dotnet build --configuration Release

test_script:
- pwsh: dotnet test "./PatternMatching.Tests/PatternMatching.Tests.csproj" --no-build --configuration Release

deploy_script:
- pwsh: .\Release-Docs
